---
kind: pipeline
type: ssh
name: BD
server:
  host: 
    from_secret: ssh_host
  user: 
    from_secret: ssh_user
  password:
    from_secret: ssh_password
steps:
- name: BD-scan
  commands:
  - curl -O https://detect.synopsys.com/detect8.sh
  - bash -x detect8.sh --blackduck.trust.cert=true --detect.project.name=test-docker  --detect.projct.version.name=imagScan --detect.project.code.location.name=test-docker_imagScan --detect.project.version.phase=RELEASED --detect.project.version.distribution=EXTERNAL --detect.tools.excluded=DETECTOR --detect.docker.image=ljw4010/ljw4010  --blackduck.offline.mode=true 
trigger:
  branch:
  - test1
